### ISSUE TITLE
Return error when call read_kudu_table function

### ISSUE THREAD

**Issue by larryxia-ddl** [bkvarda/kudusparklyr#3]
I got error when call function read_kudu_table. get_kudu_table and kudu_table_exists works fine. I am new to kudusparlyr, please advise how can I fix this issue. 

 Thanks
 
Larry

> df <- read_kudu_table(sc, "impala::kudu_poc.ktb1")
Error in UseMethod("invoke") : 
  no applicable method for 'invoke' applied to an object of class "NULL"
> kudu_table_exists(sc, "impala::kudu_poc.ktb1")
[1] TRUE
> tbl <- get_kudu_table(sc, "impala::kudu_poc.ktb1")
> get_impala_ddl(sc, tbl)
[1] "CREATE EXTERNAL TABLE `impala::kudu_poc.ktb1` STORED AS KUDU TBLPROPERTIES('kudu.table_name'='impala::kudu_poc.ktb1','kudu.master_addresses'='localhost:7051');"

**Comment by bkvarda** [comment]
Looks like sparklyr stopped exposing $hive_context as a property of the spark_connection object, and has instead made the hive_context() function available to get the hive context/spark session. Fixed in commit 983013f
