### ISSUE TITLE
Kudu 1.5.0 with Spark 1.6.0

### ISSUE THREAD

**Issue by nachti** [bkvarda/kudusparklyr#6]
Hi Brandon!
Thanks for this great package, which worked well for me using Cloudera's CDH 5.10 distribution.
Changing to CDH 5.13 there is a newer version of Kudu (1.5.0), with the same (old) Spark 1.6.0
Is it possible to include the respective jars?
Thanks in advance,
Gerhard

**Comment by bkvarda** [comment]
Hi Gerhard,

I've added the requested JARs for Spark 1.6/Kudu 1.5.0 as well as Spark 2.2/Kudu 1.5.0. Let me know if that works for you.

**Comment by nachti** [comment]
Thank you so much Brandon!
It's working fine again now.
The only thing I've to do for Spark 1.6.0 is to add the hive context of my spark connection (sc):

```r
sc <- spark_connect(<args>)
sc <- kudu_context(sc, <args>)
### add element with hive_context in Spark 1.6
### required for kudusparklyr::read_kudu_table
sc$hive_context <- hive_context(sc)
```

Cheers,
Gerhard
